---
- block:
  - name: Ensure libvirt image directory is present
    file:
      path: "{{ image_path }}"
      state: directory
      mode: 0711
      owner: root
      group: root
    become: yes

  - name: Create a temporary directory used when provisioning
    tempfile:
      state: directory
      suffix: provision_vm
    register: temp_dir

  - set_fact:
      runtime_tempdir: "{{ temp_dir.path }}"

  - name: Set ownership and permissions for the temporary directory
    file:
      path: "{{ runtime_tempdir }}"
      state: directory
      mode: 0700
      owner: qemu
      group: qemu
    become: yes

  # guest_type defaults to kickstart, but can be image, pxe, or iso
  - name: Prepare to start the VM
    include: "{{ guest_type }}-guest.yml"

  - name: Generate deploying VM script
    template:
      src: virt-install-script.sh.j2
      dest: "{{ runtime_tempdir }}/virt-install-script.sh"
      mode: 0770
      owner: root
      group: root
    become: yes

  - name: Start deploying the VM
    command: "bash {{ runtime_tempdir }}/virt-install-script.sh"
    args:
      creates: "/etc/libvirt/qemu/{{ inventory_hostname }}.xml"
    become: yes
    environment: "{{ env_virt_install | default(omit) }}"
    register: virt_install_job

  delegate_to: "{{ hyper }}"
...
