---
- block:
  - name: Ensure guestfish is installed
    yum:
      name: libguestfs-tools
      state: installed
    become: yes

  - name: Download specified image
    get_url:
      url: "{{ image_url_prefix }}/{{ image_name }}"
      dest: "{{ image_path}}/{{ image_name }}"
      mode: 0400
      owner: qemu
      backup: yes
    become: yes

  - name: Generate cloud-init meta-data and user-data
    template:
      src: "{{ item }}.j2"
      dest: "{{ runtime_tempdir }}/{{ item }}"
      mode: 0400
      owner: qemu
      group: qemu
    with_items:
      - meta-data
      - user-data
    become: yes

  - name: Generate ISO for cloud-init
    command: >
      genisoimage -output {{ runtime_tempdir }}/cloud-init.iso -volid \
      cidata -joliet -rock {{ runtime_tempdir }}/user-data \
      {{ runtime_tempdir }}/meta-data
    become: yes

  - name: Set ownership and permissions for the cloud-init ISO
    file:
      name: "{{ runtime_tempdir }}/cloud-init.iso"
      mode: 0400
      owner: qemu
      group: qemu
    become: yes

  - name: Copy the ISO and qcow images
    copy:
      remote_src: true
      src: "{{ item.src }}"
      dest: "{{ image_path }}/{{ fqdn }}.{{ item.format }}"
      mode: "{{ item.mode }}"
      owner: qemu
      group: qemu
    with_items:
      - src: "{{ runtime_tempdir }}/cloud-init.iso"
        format: iso
        mode: "0400"
      - src: "{{ image_path }}/{{ image_name }}"
        format: qcow2
        mode: "0600"
    become: yes

  - name: Include optional modification for the image
    include: "{{ provision_vm_image_fixup_hook }}"
    when: provision_vm_image_fixup_hook is defined

  - name: Copy the guestfish script fixing CentOS 7 image to the hypervisor
    template:
      src: modify-centos-image.guestfish.j2
      dest: "{{ runtime_tempdir }}/modify-centos-image.guestfish"
      mode: 0600
      owner: qemu
      group: qemu
    become: yes
    when:
      - "'centos' in image_name.lower()"
      - "'7' in image_name"

  - name: Fix CentOS 7 image (disabling DHCP on eth0)
    command: >
      /usr/bin/guestfish --rw -a {{ image_path}}/{{ fqdn }}.qcow2 \
       -f {{ runtime_tempdir }}/modify-centos-image.guestfish
    environment:
      LIBGUESTFS_BACKEND: direct # Fix first run on clean host with no VMs
    become: yes
    when:
      - "'centos' in image_name.lower()"
      - "'7' in image_name"

  - name: Resize image to use the whole disk
    command: "qemu-img resize {{ image_path}}/{{ fqdn }}.qcow2 {{ root_disk_size }}G"
    become: yes

  # Used by the virt-install-command.j2 template to configure the root disk
  - name: Set the disk fact
    set_fact:
      disks:
        - path: "{{ image_path}}/{{ fqdn }}.qcow2"
          size: "{{ root_disk_size }}"
          format: qcow2

  delegate_to: "{{ hyper }}"
...
