---
- block:
  - name: Download specified image
    get_url:
      url: "{{ image_url_prefix }}/{{ image_name }}"
      dest: "{{ image_path }}/{{ image_name }}"
      mode: 0400
      owner: qemu
      backup: yes
    become: yes

  - name: Copy the ISO boot image
    copy:
      remote_src: true
      src: "{{ image_path }}/{{ image_name }}"
      dest: "{{ image_path }}/{{ fqdn }}.iso"
      mode: 0400
      owner: qemu
      group: qemu
    become: yes

  - name: Delete old hard disk image
    file:
      path: "{{ image_path }}/{{ fqdn }}.qcow2"
      state: absent
    become: yes

  - name: Create new hard disk image
    command: "qemu-img create -f qcow2 {{ image_path}}/{{ fqdn }}.qcow2 {{ root_disk_size }}G"
    become: yes

  - name: Set ownership and permissions for the hard disk image
    file:
      path: "{{ image_path }}/{{ fqdn }}.qcow2"
      owner: qemu
      group: qemu
      mode: 0600
    become: yes

  # Used by the virt-install-command-iso.j2 template to configure the root disk
  - name: Set the disk fact
    set_fact:
      disks:
        - path: "{{ image_path}}/{{ fqdn }}.qcow2"
          size: "{{ root_disk_size }}"
          format: qcow2

  delegate_to: "{{ hyper }}"
...
