---
- name: Check hyper is defined
  assert:
    that: hyper is defined
    msg: "hyper must be set to a hypervisor host where you want VMs to run"

# Most of this code will run on the hypervisor as defined by the hyper varible

- name: gather hypervisor facts
  setup:
  delegate_to: "{{ hyper }}"

- name: Check if VM exists already
  virt:
    name: "{{ inventory_hostname }}"
    command: get_xml
    uri: qemu:///system
  register: guest_exists
  ignore_errors: true
  become: yes
  delegate_to: "{{ hyper }}"

- name: Create a new guest if needed
  include: create-new-guest.yml
  when: guest_exists | failed

- name: Wait for boot if needed
  include: wait-for-boot.yml
  when: guest_exists | failed

# Now the VM should be booting and we can connect directly to the host for the first time
- name: Get facts from new vm (image based deployments only)
  setup:
  register: setup
  until: setup | succeeded
  retries: 3
  delay: 20
  when: guest_type == 'image'

- name: Cleanup files from guest)_type
  include: "{{ guest_type }}-cleanup.yml"

- name: Cleanup common files
  include: cleanup.yml
...
