---
- name: Check hyper is defined
  assert:
    that: hyper is defined
    msg: "hyper must be set to a hypervisor host where you want VMs to run"

# Most of this code will run on the hypervisor as defined by the hyper varible
# We use a block to reduce repeating the 'delegate_to' for every task
- block:

  - name: gather hypervisor facts
    setup:

  - name: group hypervisors by distro
    group_by:
      key: "os_{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"

  - name: Check if VM exists already
    virt:
      name: "{{ inventory_hostname }}"
      command: get_xml
      uri: qemu:///system
    register: guest_exists
    ignore_errors: true
    become: yes

  - name: Ensure libvirt image directory is present
    file:
      path: "{{ image_path }}"
      state: directory
      mode: "0711"
      owner: root
      group: root
    become: yes
    when: guest_exists | failed

  - name: create a remote temp directory
    command: mktemp -d "{{ provision_tempdir }}/provision_vm.XXXX"
    register: temp_dir
    when: guest_exists | failed

  - name: Set playbook temp_dir as fact
    set_fact:
      runtime_tempdir: "{{ temp_dir.stdout }}"
    when: guest_exists | failed

  - name: Change ownership of temp directory
    file:
      path: "{{ runtime_tempdir }}"
      state: directory
      mode: 0700
      owner: qemu
      group: qemu
    become: yes
    when: guest_exists | failed

  delegate_to: "{{ hyper }}"
  # End of block

- name: Prepare to start the guest using Kickstart
  include: kickstart-guest.yml
  when:
    - guest_type is not defined or (guest_type != "image" and guest_type!="iso")
    - guest_exists | failed

- name: Prepare to start the guest using an OpenStack image
  include: image-guest.yml
  when:
    - guest_type is defined
    - guest_type == 'image'
    - guest_exists | failed

- name: Prepare to start the guest using an ISO image
  include: iso-guest.yml
  when:
    - guest_type is defined
    - guest_type == 'iso'
    - guest_exists | failed

- name: Deploy script to deploy VM
  template:
    src: virt-install-script.sh.j2
    dest: "{{runtime_tempdir}}/virt-install-script.sh.j2"
  become: yes
  delegate_to: "{{ hyper }}"
  when: guest_exists | failed

- name: Deploy script to deploy VM from ISO image
  template:
    src: virt-install-script-iso.sh.j2
    dest: "{{runtime_tempdir}}/virt-install-script-iso.sh.j2"
  become: yes
  delegate_to: "{{ hyper }}"
  when: guest_exists | failed

- name: Start deployment of VM
  command: "bash {{runtime_tempdir}}/virt-install-script.sh.j2"
  args:
    creates: "/etc/libvirt/qemu/{{ inventory_hostname }}.xml"
  become: yes
  environment: "{{ env_virt_install | default(omit) }}"
  delegate_to: "{{ hyper }}"
  register: virt_install_job
  when: 
    - guest_exists | failed
    - guest_type is undefined or guest_type == 'image'

- name: Start deployment of VM
  command: "bash {{runtime_tempdir}}/virt-install-script-iso.sh.j2"
  args:
    creates: "/etc/libvirt/qemu/{{ inventory_hostname }}.xml"
  become: yes
  environment: "{{ env_virt_install | default(omit) }}"
  delegate_to: "{{ hyper }}"
  register: virt_install_job
  when: 
    - guest_exists | failed 
    - guest_type == 'iso'

  # Force ansible to know the IP address of this host so it can connect
  # This fixes things if you don't have the IP address in DNS or /etc/hosts.
- name: Set ansible_host to the new guest IP address
  set_fact: ansible_host={{ internal_ip }}

- name: wait for VM to become available before continuing
  wait_for:
    port: 22
    host: "{{ provisioning_wait_for_addr | default(ansible_host) }}"
    timeout: 300
    search_regex: OpenSSH
  delegate_to: "{{ bastion_host | default(hyper) }}"
  when: guest_exists | failed

  # This attempts to handle the common case where the new VM has a new and
  # unknown host key, because you just rebuilt this VM. Modern linux distro's
  # protect ~/.ssh linux using selinux so you'll need libselinux-python.
  # libselinux doesn't work in python virtual envs without screwing about,
  # see:
  # https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/
  # Since this is a hassle this task is set to ignore errors. Pull requests
  # are welcome! ;-)
- name: Clear known_hosts for new VM
  known_hosts:
    name: "{{ item }}"
    state: absent
  when: guest_exists | failed
  delegate_to: localhost
  with_items:
    - "{{ ansible_host }}"
    - "{{ inventory_hostname }}"
  ignore_errors: yes

- name: Wait for ssh key configuration by cloud-init
  pause: seconds=5
  when:
    - guest_exists | failed
    - guest_type is defined
    - guest_type == 'image'

# Now the VM should be booting and we can connect directly to the host for the first time
- name: Get facts from new vm (image based deployments only)
  setup:
  register: setup
  until: setup | succeeded
  retries: 3
  delay: 10
  when:
    - guest_type is defined
    - guest_type == 'image'

- name: cleanup temporary install files
  file:
    path: "{{ runtime_tempdir }}"
    state: absent
  become: yes
  delegate_to: "{{ hyper }}"
  when: guest_exists | failed
...
