---
- name: Check if hyper is defined
  assert:
    that: hyper is defined
    msg: "hyper must be set to a hypervisor host where you want VMs to run"

# Most of this code will run on the hypervisor as defined by the hyper variable
- name: Gather hypervisor facts
  setup:
  delegate_to: "{{ hyper }}"

- name: Check if the VM already exists
  virt:
    name: "{{ inventory_hostname }}"
    command: get_xml
    uri: qemu:///system
  register: guest_exists
  ignore_errors: true
  become: yes
  delegate_to: "{{ hyper }}"

- name: Create a new guest if needed
  include: create-new-guest.yml
  when: guest_exists | failed
  # Skip the whole include, not all the tasks
  static: False

- name: Wait for boot if needed
  include: wait-for-boot.yml
  when: guest_exists | failed
  # Skip the whole include, not all the tasks
  static: False

# Now the VM should be booting, and we can connect to it
- name: Get facts from the new VM
  setup:
  register: setup
  until: setup | succeeded
  retries: 3
  delay: 20
  when: guest_type == 'image'

- name: Clean up when it is an image guest
  include: "{{ guest_type }}-cleanup.yml"
  when: guest_type == 'image'

- name: Commonly clean up
  include: cleanup.yml
...
