---
- block:
  - name: Delete old root disk image
    file:
      path: "{{ image_path}}/{{ fqdn }}.qcow2"
      state: absent
    become: yes

  - name: Delete old extra disk image if exists
    file:
      path: "{{ image_path}}/{{ fqdn }}_extra.qcow2"
      state: absent
    become: yes
    when: extra_disk_size is defined

  - name: Create new root disk image
    command: "qemu-img create -f qcow2 {{ image_path}}/{{ fqdn }}.qcow2 {{ root_disk_size }}G"
    become: yes

  - name: Create new extra disk image if needed
    command: "qemu-img create -f qcow2 {{ image_path}}/{{ fqdn }}_extra.qcow2 {{ extra_disk_size }}G"
    become: yes
    when: extra_disk_size is defined

  - name: Set ownership and permissions for the root disk image
    file:
      path: "{{ image_path}}/{{ fqdn }}.qcow2"
      owner: qemu
      group: qemu
      mode: 0600
    become: yes

  - name: Set ownership and permissions for the extra disk image if exists
    file:
      path: "{{ image_path}}/{{ fqdn }}_extra.qcow2"
      owner: qemu
      group: qemu
      mode: 0600
    become: yes
    when: extra_disk_size is defined

  - name: Set the root disk fact
    set_fact:
      disks:
        - path: "{{ image_path}}/{{ fqdn }}.qcow2"
          size: "{{ root_disk_size }}"
          format: qcow2

  - name: Set the extra disk fact
    set_fact:
      extra_disks:
        - path: "{{ image_path}}/{{ fqdn }}_extra.qcow2"
          size: "{{ extra_disk_size }}"
          format: qcow2
    when: extra_disk_size is defined

  delegate_to: "{{ hyper }}"
