---
- name: Wait for VM to be accessible via SSH
  local_action: wait_for
  args:
    port: 22
    host: "{{ ansible_host }}"
    timeout: 600
    search_regex: OpenSSH
  when:
    - guest_exists | failed

  # This attempts to handle the common case where the new VM has a new and
  # unknown host key, because you just rebuilt this VM. Modern linux distro's
  # protect ~/.ssh linux using selinux so you'll need libselinux-python.
  # libselinux doesn't work in python virtual envs without screwing about,
  # see:
  # https://dmsimard.com/2016/01/08/selinux-python-virtualenv-chroot-and-ansible-dont-play-nice/
  # Since this is a hassle this task is set to ignore errors. Pull requests
  # are welcome! ;-)
- name: Remove VM's old host keys
  local_action: known_hosts
  args:
    name: "{{ item }}"
    state: absent
  when: guest_exists | failed
  with_items:
    - "{{ ansible_host }}"
    - "{{ inventory_hostname }}"
  ignore_errors: yes

- name: Wait for ssh key configured by cloud-init
  pause:
    seconds: 5
  when:
    - guest_exists | failed
    - guest_type == 'image'
...
